export const CLIENTS_CONNECTION = 'CLIENTS_CONNECTION';
export const TENANT_CONNECTION = 'TENANT_CONNECTION';

//primary models
export const COMPANY_MODEL = 'COMPANY_MODEL';
export const MEMBER_MODEL = 'MEMBER_MODEL';
export const APPOINTMENT_MODEL = 'APPOINTMENT_MODEL';
export const SERVICE_MODEL = 'SERVICE_MODEL';

//clients models
export const CLIENT_COMPANY_MODEL = 'CLIENT_COMPANY_MODEL';
export const CLIENT_MEMBER_MODEL = 'CLIENT_MEMBER_MODEL';
export const CLIENT_APPOINTMENT_MODEL = 'CLIENT_APPOINTMENT_MODEL';
export const CLIENT_SERVICE_MODEL = 'CLIENT_SERVICE_MODEL';
